[package]
name = "meufchrer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serenity = "0.12.2"
shuttle-runtime = "0.46.0"
tokio = "1.38.0"
tracing = "0.1.40"

[build-dependencies]
anyhow = "1.0.86"
git2 = "0.19.0"
